name: Update Age Badge

on:
  schedule:
    - cron: '0 0 1 5 *' # Cada 1 de mayo a medianoche
  workflow_dispatch: # Permite ejecutarlo manualmente también

jobs:
  update-age:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Calculate Age
        run: |
          BIRTH_YEAR=2004
          CURRENT_YEAR=$(date +'%Y')
          AGE=$((CURRENT_YEAR - BIRTH_YEAR))
          echo "{\"schemaVersion\": 1, \"label\": \"Age\", \"message\": \"$AGE\", \"color\": \"blue\"}" > data.json

      - name: Commit Age file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.json
          git commit -m "Update age badge" || echo "No changes to commit"
          git push
